-- The original Lackluster mappings are retained here as a palette-independent
-- editor theme. `theme.build` supplies fresh semantic colors on every render.
return function(color, special)
    return {
        none = "none",
        ui = {
            use_undercurl = true,
            fg_end_of_buffer = special.main_background,
            fg_normal = color.gray8,
            bg_normal = special.main_background,
            fg_whitespace = special.whitespace,
            fg_icon = color.gray4,
            fg_button = color.gray5,
            bg_button = special.popup_background,
            fg_button_active = color.gray4,
            bg_button_active = color.gray8,
            fg_title = color.gray5,
            fg_statusline_nc = color.gray4,
            bg_statusline_nc = color.gray1,
            fg_statusline = color.gray7,
            bg_statusline = special.statusline,
            fg_tab_nc = color.gray4,
            bg_tab_nc = color.gray2,
            fg_tab_active = color.gray1,
            bg_tab_active = color.gray8,
            fg_line_num = color.gray4,
            fg_line_num_cur = color.gray7,
            fg_border = color.gray4,
            bg_colorcolumn = color.gray1,
            bg_cursorline = color.gray2,
            bg_visual = color.gray8,
            fg_visual = color.black,
            fg_search = color.black,
            bg_search_item = color.lack,
            bg_search_cur = color.gray8,
            bg_scrollbar = color.gray3,
            fg_scrollbar = color.gray5,
            fg_popup = color.gray6,
            bg_popup = special.popup_background,
            fg_menu = color.gray6,
            bg_menu = special.menu_background,
            fg_telescope = color.gray8,
            bg_telescope = special.main_background,
        },
        fs = {
            dir = color.gray5,
            file = color.luster,
            exec = color.green,
            link = color.lack,
            binary_data = color.gray6,
            socket = color.gray6,
        },
        plugin_telescope = {
            fg_normal = color.gray8,
            bg_normal = special.main_background,
            fg_results = color.gray5,
            bg_selection = color.gray3,
            fg_preview = color.black,
            bg_preview = color.gray9,
            fg_counter = color.gray7,
            fg_border = color.gray7,
        },
        plugin_cmp = {
            kind = color.gray7,
            snippet = color.lack,
            deprecated = color.gray4,
        },
        plugin_which_key = {
            key = color.gray5,
            group = color.lack,
            separator = color.gray4,
        },
        plugin_lazy = {
            special = color.gray5,
            comment = color.lack,
        },
        plugin_trouble = {
            normal = color.gray5,
            code = color.gray6,
        },
        plugin_tree = {
            bookmark = color.lack,
        },
        plugin_mason = {
            highlight = color.lack,
            header = color.lack,
        },
        plugin_flash = {
            fg_label = special.popup_background,
            bg_label = color.blue,
            fg_match = color.gray6,
            bg_match = special.main_background,
            fg_current = color.black,
            bg_current = color.gray9,
        },
        plugin_navic = {
            icon = color.gray6,
            text = color.gray9,
        },
        plugin_headline = {
            bg_headline = color.gray2,
            fg_headline = color.gray4,
            bg_code_block = color.gray1,
            fg_dash = color.gray4,
        },
        plugin_scrollbar = {
            bg = color.gray2,
            cursor = color.gray4,
        },
    }
end
